// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace myMLApp
{
    public partial class SentimentModel
    {
        /// <summary>
        /// model input class for SentimentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"State")]
            public float State { get; set; }

            [ColumnName(@"Num of Communities")]
            public float Num_of_Communities { get; set; }

            [ColumnName(@"Num Infected")]
            public float Num_Infected { get; set; }

            [ColumnName(@"Num Infected Nearby")]
            public float Num_Infected_Nearby { get; set; }

            [ColumnName(@"Times Traveled")]
            public float Times_Traveled { get; set; }

            [ColumnName(@"Total Spawn Count")]
            public float Total_Spawn_Count { get; set; }

            [ColumnName(@"Outcome")]
            public float Outcome { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SentimentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"State")]
            public float State { get; set; }

            [ColumnName(@"Num of Communities")]
            public float Num_of_Communities { get; set; }

            [ColumnName(@"Num Infected")]
            public float Num_Infected { get; set; }

            [ColumnName(@"Num Infected Nearby")]
            public float Num_Infected_Nearby { get; set; }

            [ColumnName(@"Times Traveled")]
            public float Times_Traveled { get; set; }

            [ColumnName(@"Total Spawn Count")]
            public float Total_Spawn_Count { get; set; }

            [ColumnName(@"Outcome")]
            public float Outcome { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SentimentModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
